### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by iTzAndrew33212** [shreyop200/AuthUI#1]
Hi there

Just curious if the passwords are meant to reset on restarting your server..
Need to always create a new password once the server restarts every 8hrs..... For cpu

Take care
Andrew

**Comment by shreyop200** [comment]
> Hi there
> 
> Just curious if the passwords are meant to reset on restarting your server.. Need to always create a new password once the server restarts every 8hrs..... For cpu
> 
> Take care Andrew

passwords dont get reset, it is saved in the database of the plugin's data folder, the passwords are always saved until you unlink that user, i will be adding the unlink soon

**Comment by iTzAndrew33212** [comment]
do you have discord or anything, I can show you vid of what is happening, restarting server causes password loss

**Comment by shreyop200** [comment]
> do you have discord or anything, I can show you vid of what is happening, restarting server causes password loss

Sure, shreyansh#0 ( shreyansh )
